web:
   restart: always
   build: apache
   ports:
      - "80:80"
   volumes:
      - /var/www:/var/www
      - /var/docker/apache2withphpFPM/site:/etc/apache2/sites-enabled
   environment:
      - ALLOW_OVERRIDE=true
   links:
      - php:php

php:
   restart: always
   build: php-fpm
   ports:
      - "9000:9000"
   volumes:
      - /var/www:/var/www
   links:
      - mysqlserveur:mysql

mysqlserveur:
   image: mariadb
   restart: always
   volumes:
      - /var/docker/datamysql:/var/lib/mysql
   ports :
      - "3306:3306"
   environment:
      - MYSQL_ROOT_PASSWORD=root

phpmyadmin:
   image: corbinu/docker-phpmyadmin
   restart: always
   ports :
      - "8080:80"
   environment:
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=root
   links:
      - mysqlserveur:mysql