web:
   restart: always
   build: apache
   ports:
      - "80:80"
   volumes:
      - /var/www:/var/www
      - /var/docker/apache2withphpFPM/site:/etc/apache2/sites-enabled
   environment:
      - ALLOW_OVERRIDE=true
   links:
      - php:php
      - db:db

php:
   restart: always
   build: php-fpm
   ports:
      - "9000:9000"
   volumes:
      - /var/www:/var/www
   links:
      - db:db

db:
 image: mysql
 restart: always
 volumes:
  - /var/lib/boot2docker/mysql:/var/lib/mysql
 environment:
  - MYSQL_ROOT_PASSWORD=root